### PR TITLE
Feat/segmenteddownloads

### PR DESCRIPTION
**Pull request by luhamoza**
add dropdown for link editions download in data catalogue

### CODE REVIEW

**Comment by amalasyrafs** [comment]
Why are there so many merged commit here? Did you start working from main or staging branch?

**Comment by luhamoza** [comment]
> Why are there so many merged commit here? Did you start working from main or staging branch? @luhamoza

my bad here, i think i started working from main branch, should i submit a new pr from staging branch ?

**Comment by amalasyrafs** [comment]
> > Why are there so many merged commit here? Did you start working from main or staging branch? @luhamoza
> 
> my bad here, i think i started working from main branch, should i close this one and submit a new pr from staging branch ?

if you could change it without much of a hassle, yes please

**Comment by luhamoza** [comment]
> > > Why are there so many merged commit here? Did you start working from main or staging branch? @luhamoza
> > 
> > 
> > my bad here, i think i started working from main branch, should i close this one and submit a new pr from staging branch ?
> 
> if you could change it without much of a hassle, yes please

okay noted, will close this one, and create new pr

**Pull request closed without merging**
